# fly.toml app configuration file generated for wdcc-website-v4-staging on 2024-12-02T14:11:55+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wdcc-website-v4-staging'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
