import type { Config } from "tailwindcss";

export default {
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        fontFamily: {
            /* TODO Set when finalised */
            font1: ["sans-serif"],
            sans: ["sans-serif"],
        },
        fontWeight: {
            thin: "300",
            light: "400",
            normal: "500",
            semibold: "600",
            bold: "700",
            extrabold: "800",
        },
        fontSize: {
            /* Type scaling TBA, modify where needed */
            xs: "0.8rem",
            sm: "0.9rem",
            md: "1.125rem",
            lg: "1.25rem",
            xl: "1.6rem",
            "2xl": "2rem",
            "3xl": "2.4rem",
            "4xl": "3rem",
            "5xl": "3.8rem",
        },
        extend: {
            colors: {
                background: "var(--background)",
                foreground: "var(--foreground)",
                gray: {
                    900: "var(--gray-900)",
                    800: "var(--gray-800)",
                    700: "var(--gray-700)",
                    600: "var(--gray-600)",
                    500: "var(--gray-500)",
                    400: "var(--gray-400)",
                    300: "var(--gray-300)",
                    250: "var(--gray-250)",
                    200: "var(--gray-200)",
                    150: "var(--gray-150)",
                    100: "var(--gray-100)",
                    50: "var(--gray-050)",
                    20: "var(--gray-020)",
                    10: "var(--gray-010)",
                },
                orange: {
                    brand: "var(--orange-brand)",
                    900: "var(--orange-900)",
                    800: "var(--orange-800)",
                    750: "var(--orange-750)",
                    700: "var(--orange-700)",
                    600: "var(--orange-600)",
                    500: "var(--orange-500)",
                    400: "var(--orange-400)",
                    300: "var(--orange-300)",
                    200: "var(--orange-200)",
                    150: "var(--orange-150)",
                    100: "var(--orange-100)",
                    50: "var(--orange-050)",
                    20: "var(--orange-020)",
                },
                yellow: {
                    brand: "var(--yellow-brand)",
                    900: "var(--yellow-900)",
                    800: "var(--yellow-800)",
                    750: "var(--yellow-750)",
                    700: "var(--yellow-700)",
                    600: "var(--yellow-600)",
                    500: "var(--yellow-500)",
                    400: "var(--yellow-400)",
                    300: "var(--yellow-300)",
                    200: "var(--yellow-200)",
                    150: "var(--yellow-150)",
                    100: "var(--yellow-100)",
                    50: "var(--yellow-050)",
                    20: "var(--yellow-020)",
                },
                blue: {
                    brand: "var(--blue-brand)",
                    900: "var(--blue-900)",
                    800: "var(--blue-800)",
                    750: "var(--blue-750)",
                    700: "var(--blue-700)",
                    600: "var(--blue-600)",
                    500: "var(--blue-500)",
                    400: "var(--blue-400)",
                    300: "var(--blue-300)",
                    200: "var(--blue-200)",
                    150: "var(--blue-150)",
                    100: "var(--blue-100)",
                    50: "var(--blue-050)",
                    20: "var(--blue-020)",
                },
                purple: {
                    brand: "var(--purple-brand)",
                    900: "var(--purple-900)",
                    800: "var(--purple-800)",
                    750: "var(--purple-750)",
                    700: "var(--purple-700)",
                    600: "var(--purple-600)",
                    500: "var(--purple-500)",
                    400: "var(--purple-400)",
                    300: "var(--purple-300)",
                    200: "var(--purple-200)",
                    150: "var(--purple-150)",
                    100: "var(--purple-100)",
                    50: "var(--purple-050)",
                    20: "var(--purple-020)",
                },
            },
        },
    },
    plugins: [],
} satisfies Config;
