import { HeroPage } from "@/payload/payload-types";

export const mockHeroPageData: HeroPage = {
    id: 1,
    hero: {
        title: "WEB DEVELOPMENT AND CONSULTING CLUB",
        blurb: "We connect tomorrow’s developers, designers, and tech leaders with the real-world experience and opportunities that ",
    },
    thisIsWDCC: {
        description:
            "We’re a student club that aims to bridge the gap between university knowledge and real-world expertise. We run projects with real clients to solve challenging technical problems, and conduct a range of events to better equip tomorrow’s talent. 🚀",
        whatWeDo: [
            {
                id: "67c2b48c3b29733fe0ed431b",
                index: "01",
                title: "Projects",
                slug: "projects",
                description:
                    "We provide opportunities for students to work in teams to deliver projects for real-world clients - gaining real industry expertise alongside motivated peers.",
                variant: "blue",
            },
            {
                id: "67c2b49f3b29733fe0ed431c",
                index: "02",
                title: "Events",
                slug: "events",
                description:
                    "We hold various social events, competitions, and mixers to bring Auckland’s tech students together - to yap, make friends, and develop their best network.",
                variant: "green",
            },
            {
                id: "67c2b4b33b29733fe0ed431d",
                index: "03",
                title: "Workshops",
                slug: "workshops",
                description:
                    "We host a range of workshops to teach members the things they’ll need to thrive in our projects, covering plenty of crucial development, tech, and people skills.",
                variant: "yellow",
            },
        ],
    },
    sponsorSection: {
        gold: [
            {
                id: 9,
                href: "https://www.partly.com/",
                alt: "partly",
                prefix: "partners",
                updatedAt: "2025-03-01T07:42:14.573Z",
                createdAt: "2025-03-01T07:42:14.491Z",
                url: "/api/partners/file/partly_logo_black.svg",
                thumbnailURL: null,
                filename: "partly_logo_black.svg",
                mimeType: "image/svg+xml",
                filesize: 1647,
                width: 708,
                height: 99,
                focalX: null,
                focalY: null,
            },
            {
                id: 11,
                href: "https://www.fonterra.com/nz/en.html",
                alt: "Fonterra Logo",
                prefix: "partners",
                updatedAt: "2025-03-08T09:27:26.486Z",
                createdAt: "2025-03-08T09:27:26.082Z",
                url: "/api/partners/file/Fonterra_Flat.webp",
                thumbnailURL: null,
                filename: "Fonterra_Flat.webp",
                mimeType: "image/webp",
                filesize: 33272,
                width: 1200,
                height: 676,
                focalX: 50,
                focalY: 50,
            },
            {
                id: 14,
                href: "https://www.figured.com/",
                alt: "Figured Logo (Blue)",
                prefix: "partners",
                updatedAt: "2025-03-08T09:34:55.504Z",
                createdAt: "2025-03-08T09:34:21.618Z",
                url: "/api/partners/file/Figured%20logo%20blue.webp",
                thumbnailURL: null,
                filename: "Figured logo blue.webp",
                mimeType: "image/webp",
                filesize: 4768,
                width: 356,
                height: 126,
                focalX: 50,
                focalY: 50,
            },
        ],
        silver: [
            {
                id: 3,
                href: "https://www.bes.au/",
                alt: "Jane Street",
                prefix: "partners",
                updatedAt: "2025-03-01T07:38:29.510Z",
                createdAt: "2025-03-01T07:38:29.234Z",
                url: "/api/partners/file/Jane%20street.webp",
                thumbnailURL: null,
                filename: "Jane street.webp",
                mimeType: "image/webp",
                filesize: 15614,
                width: 400,
                height: 400,
                focalX: 50,
                focalY: 50,
            },
            {
                id: 4,
                href: "https://www.ey.com/en_nz",
                alt: "EY",
                prefix: "partners",
                updatedAt: "2025-03-01T07:38:47.320Z",
                createdAt: "2025-03-01T07:38:47.172Z",
                url: "/api/partners/file/EY.webp",
                thumbnailURL: null,
                filename: "EY.webp",
                mimeType: "image/webp",
                filesize: 20692,
                width: 742,
                height: 400,
                focalX: 50,
                focalY: 50,
            },
            {
                id: 5,
                href: "https://datacom.com/nz/en",
                alt: "datacom",
                prefix: "partners",
                updatedAt: "2025-03-01T07:39:09.787Z",
                createdAt: "2025-03-01T07:39:09.664Z",
                url: "/api/partners/file/datacom.webp",
                thumbnailURL: null,
                filename: "datacom.webp",
                mimeType: "image/webp",
                filesize: 14910,
                width: 1005,
                height: 400,
                focalX: 50,
                focalY: 50,
            },
            {
                id: 6,
                href: "https://www.sandfield.co.nz/",
                alt: "sandfield",
                prefix: "partners",
                updatedAt: "2025-03-01T07:40:27.374Z",
                createdAt: "2025-03-01T07:40:27.217Z",
                url: "/api/partners/file/sandfield.webp",
                thumbnailURL: null,
                filename: "sandfield.webp",
                mimeType: "image/webp",
                filesize: 29978,
                width: 974,
                height: 400,
                focalX: 50,
                focalY: 50,
            },
            {
                id: 8,
                href: "https://serato.com/",
                alt: "serato",
                prefix: "partners",
                updatedAt: "2025-03-01T07:41:46.184Z",
                createdAt: "2025-03-01T07:41:45.955Z",
                url: "/api/partners/file/serato_black.webp",
                thumbnailURL: null,
                filename: "serato_black.webp",
                mimeType: "image/webp",
                filesize: 27682,
                width: 1535,
                height: 400,
                focalX: 50,
                focalY: 50,
            },
            {
                id: 7,
                href: "https://kpmg.com/nz/en/home.html",
                alt: "KPMG",
                prefix: "partners",
                updatedAt: "2025-03-01T07:40:46.973Z",
                createdAt: "2025-03-01T07:40:46.870Z",
                url: "/api/partners/file/KPMG.webp",
                thumbnailURL: null,
                filename: "KPMG.webp",
                mimeType: "image/webp",
                filesize: 9010,
                width: 541,
                height: 400,
                focalX: 50,
                focalY: 50,
            },
            {
                id: 13,
                href: "https://www.imc.com",
                alt: "IMC Logo",
                prefix: "partners",
                updatedAt: "2025-03-08T09:32:57.479Z",
                createdAt: "2025-03-08T09:32:57.339Z",
                url: "/api/partners/file/IMC_Logo.svg.webp",
                thumbnailURL: null,
                filename: "IMC_Logo.svg.webp",
                mimeType: "image/webp",
                filesize: 27782,
                width: 1280,
                height: 238,
                focalX: 50,
                focalY: 50,
            },
        ],
        tech: [],
        community: [
            {
                id: 15,
                href: "https://sumthindumplin.co.nz/",
                alt: "Sumthin Dumplin Logo",
                prefix: "partners",
                updatedAt: "2025-03-09T20:25:31.573Z",
                createdAt: "2025-03-09T20:25:31.464Z",
                url: "/api/partners/file/sumthindumplin.png",
                thumbnailURL: null,
                filename: "sumthindumplin.png",
                mimeType: "image/png",
                filesize: 10952,
                width: 225,
                height: 225,
                focalX: 50,
                focalY: 50,
            },
            {
                id: 17,
                href: "https://lunabakehousenz.com/",
                alt: "Luna All Day Logo",
                prefix: "partners",
                updatedAt: "2025-04-07T23:53:19.192Z",
                createdAt: "2025-04-07T23:52:59.709Z",
                url: "/api/partners/file/luna-all-day-logo.png",
                thumbnailURL: null,
                filename: "luna-all-day-logo.png",
                mimeType: "image/png",
                filesize: 5986,
                width: 225,
                height: 225,
                focalX: 50,
                focalY: 50,
            },
        ],
    },
    signUpCard: {
        title: "Start your web dev journey here.",
        descriptionLineOne:
            "WDCC membership is totally free, and lets you access all kinds of member-exclusive messages, events, workshops, and more.",
        descriptionLineTwo: "Plus, at the start of the year, you can apply to join a ",
    },
    updatedAt: "2025-04-07T23:53:58.756Z",
    createdAt: "2025-03-01T07:18:51.760Z",
};
