name: Check Build

on:
  # Run on push to any branch except main
  push:
    branches:
      - "*"
      - "!main"
  # Allow manual triggers
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache Node.js dependencies
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}

      # Build with Docker
      # https://github.com/docker/build-push-action
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          secrets: |
            DATABASE_URI=${{ secrets.DATABASE_URI }} \
            PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }} \
            S3_BUCKET=${{ secrets.S3_BUCKET }} \
            S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }} \
            S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }} \
            S3_REGION=${{ secrets.S3_REGION }}
