name: Check Build

on:
  # Run on push to any branch except main
  push:
    branches:
      - "*"
      - "!main"
  # Allow manual triggers
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache Node.js dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-

      # Build with Docker
      # https://github.com/docker/build-push-action
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          secrets: |
            DATABASE_URI=${{ secrets.DATABASE_URI }} \
            PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }} \
            S3_BUCKET=${{ secrets.S3_BUCKET }} \
            S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }} \
            S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }} \
            S3_REGION=${{ secrets.S3_REGION }}
