name: Check Linting

on:
  # Run on push to any branch except main
  push:
    branches:
      - "*"
      - "!main"
  # Allow manual triggers
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache Node.js dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-

      # Set up Pnpm
      - name: Set up Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Run Prettier & ESLint
      - name: Run Prettier & ESLint
        run: pnpm run lint:ci
